# Generated by Django 5.0.2 on 2024-05-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('original_price', models.IntegerField()),
                ('current_price', models.IntegerField()),
                ('discount_percentage', models.IntegerField()),
                ('return_period', models.IntegerField()),
                ('delivery_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
